image: python:3.12-slim

stages:
  - test

before_script:
  - pip install --no-cache-dir -e ".[dev]"

unit-test:
  stage: test
  script:
    - pip install pytest
    - pytest tests/ -v
  artifacts:
    reports:
      junit: junit.xml
    when: always